quarkus:
  keycloak:
    policy-enforcer:
      enable: true
  oidc:
    auth-server-url: http://buggy-keycloak:8080/auth/realms/buggy
    client-id: buggyui
    credentials:
      secret: d6bbc4e6-ca6b-4a15-96aa-838aab3aaeef

  mongodb:
    connection-string: mongodb://buggy-mongo:27017

  log:
    level: INFO
    category:
      io.smallrye.reactive.messaging:
        level: TRACE
      de.dkutzer:
        level: TRACE



# Configures the AMQP broker credentials.
amqp-username: admin
amqp-password: admin
amqp-host: buggy-rabbitmq
amqp-port: 5672

# Configure the AMQP connector to read from the `prices` queue
mp:
  messaging:
    outgoing:
      developer:
        connector: smallrye-amqp
        address: developer
        durable: false





