spring:
  data:
    mongodb:
      host: buggy-mongo
  rabbitmq:
    host: buggy-rabbitmq
    password: admin
    username: admin
  boot:
    admin:
      client:
        url: http://buggy-sba-service:8080
        instance:
          prefer-ip: true