spring:

  data:
    mongodb:
      host: localhost

  boot:
    admin:
      client:
        enabled: false
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost
  kafka:
    bootstrap-servers: localhost:9092
  zipkin:
    enabled: true
  sleuth:
    enabled: true

logging:
  level:
    root: info
    de.dkutzer: trace
#    org.apache.kafka: trace
    org.springframework.cloud.stream: trace


management:
  metrics:
    export:
      prometheus:
        pushgateway:
          enabled: false
        enabled: false
server:
  port: 8082
