spring:
  main:
    banner-mode: "off"
  application:
    name: buggy-planning-service
  profiles:
    active: local
  jackson:
    time-zone: UTC
  cloud:
    stream:
      kafka:
        binder:
          headers: x-retries
        default:
          consumer:
            enableDlq: true
      bindings:
        developers_channel:
          destination: developers
          group: buggy-planning
          consumer:
            max-attempts: 1
        developers_error_channel_in:
          destination: error.developers.buggy-planning
          group: buggy-planning-replay
        developers_error_channel_out:
          destination: developers
        developers_parkinglot:
          destination: developers.parkinglot
        issues_error_channel_in:
          destination: error.issues.buggy-planning
          group: buggy-planning-replay
        issues_error_channel_out:
          destination: issues
        issues_parkinglot:
          destination: issues.parkinglot
        issues_channel:
          destination: issues
          group: buggy-planning
          consumer:
            max-attempts: 1
      default-binder: kafka
  kafka:
    consumer:
      client-id: ${spring.application.name}
      auto-offset-reset: earliest

  data:
    mongodb:
      database: buggy-plannings
  zipkin:
    sender:
      type: rabbit
  sleuth:
    messaging:
      enabled: true
    sampler:
      probability: 100


management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /
  endpoint:
    health:
      show-details: always
      enabled: true
  trace:
    http:
      include: REQUEST_HEADERS,RESPONSE_HEADERS,TIME_TAKEN,PRINCIPAL

