{
 "title": "IoT Portal Prod",
 "tags": [
  "IoT",
  "Portal"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "Status",
     "measurement": "docker_container_health",
     "query": "SELECT \"health_status\" FROM \"docker_container_health\" WHERE (\"com.docker.swarm.service.name\" = 'role_msa_iot-portal' AND \"host\" =~ /^msa-0[12].prod.tk-de.365farmnet.local/) AND $timeFilter",
     "select": [
      [
       { "params": [ "health_status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "com.docker.swarm.service.name", "operator": "=", "value": "role_msa_iot-portal" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ],
     "target": "select metric"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 2, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Container",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "query": "SELECT mean(\"usage_percent\") FROM \"docker_container_mem\" WHERE (\"com.docker.swarm.service.name\" = 'role_msa_iot-portal' AND \"host\" =~ /^msa-0[12].prod.tk-de.365farmnet.local/)  AND $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.swarm.service.name", "operator": "=", "value": "role_msa_iot-portal" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ],
     "target": "select metric"
    },
    {
     "alias": "Host",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"used_percent\") FROM \"mem\" WHERE (\"host\" =~ /^msa-0[12].prod.tk-de.365farmnet.local/)  AND $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Container",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.swarm.service.name", "operator": "=", "value": "role_msa_iot-portal" }
     ],
     "target": "select metric"
    },
    {
     "alias": "Host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_user\") FROM \"cpu\" WHERE (\"host\" =~ /^msa-0[12].prod.tk-de.365farmnet.local/)  AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Incoming Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "All",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT mean(\"count\") FROM \"http_server_requests\" WHERE (\"host\" =~ /^msa-0[12].prod.tk-de.365farmnet.local/ AND \"service\" = 'iot-portal') AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "iot-portal" }
     ],
     "target": "select metric"
    },
    {
     "alias": "Error",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT count(\"count\") FROM \"http_server_requests\" WHERE (\"host\" =~ /^msa-0[12].prod.tk-de.365farmnet.local/  AND \"service\" = 'iot-portal' AND \"status\" != '200') AND $timeFilter GROUP BY time(10s) fill(0)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "iot-portal" },
      { "condition": "AND", "key": "status", "operator": "!=", "value": "200" }
     ]
    }
   ]
  },
  {
   "title": "Booking Proposals",
   "type": "table",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 6 },
   "targets": [
    {
     "alias": "Active Companies",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM \"365fn_iot_iot-portal_bookingproposal_activecompanies\" WHERE (\"host\" =~ /^msa-0[12].prod.tk-de.365farmnet.local/)  AND time > now() - 7d AND \"value\" != 0  GROUP BY time(1d) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "select metric"
    },
    {
     "alias": "New Proposals",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") AS \"mean_value\" FROM \"365fn_iot_iot-portal_bookingproposal_success\" WHERE time > now() - 7d AND (\"host\" =~ /^msa-0[12].prod.tk-de.365farmnet.local/)  GROUP BY time(1d) FILL(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Failure",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") AS \"mean_value\" FROM \"365fn_iot_iot-portal_bookingproposal_failure\" WHERE time > now() - 7d AND (\"host\" =~ /^msa-0[12].prod.tk-de.365farmnet.local/)    GROUP BY time(1d) FILL(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "avg. amount of Accounts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM \"365fn_iot_iot-portal_account\" WHERE time > now() - 7d AND (\"host\" =~ /^msa-0[12].prod.tk-de.365farmnet.local/)     GROUP BY time(1d) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Booking Proposals",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Active Companies",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") AS \"mean_value\" FROM \"365fn_iot_iot-portal_bookingproposal_activecompanies\" WHERE time > now() - 7d AND (\"host\" =~ /^msa-0[12].prod.tk-de.365farmnet.local/)  GROUP BY time(1d) FILL(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "select metric"
    },
    {
     "alias": "New Proposals",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") AS \"mean_value\" FROM \"365fn_iot_iot-portal_bookingproposal_success\" WHERE time > now() - 7d AND (\"host\" =~ /^msa-0[12].prod.tk-de.365farmnet.local/)  GROUP BY time(1d) FILL(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Failures",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") AS \"mean_value\" FROM \"365fn_iot_iot-portal_bookingproposal_failure\" WHERE time > now() - 7d AND (\"host\" =~ /^msa-0[12].prod.tk-de.365farmnet.local/)   GROUP BY time(1d) FILL(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Accounts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "365fn_iot_iot-portal_account",
     "query": "SELECT mean(\"value\") FROM \"365fn_iot_iot-portal_account\" WHERE time > now() - 7d AND (\"host\" =~ /^msa-0[12].prod.tk-de.365farmnet.local/)    GROUP BY time(1d) FILL(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Accounts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "365fn_iot_iot-portal_account",
     "query": "SELECT mean(\"value\") FROM \"365fn_iot_iot-portal_account\" WHERE (\"host\" =~ /^msa-0[12].prod.tk-de.365farmnet.local/)  AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ],
     "target": "select metric"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16 } }
 ]
}