version: '3.5'

networks:
  buggy-networks:
    driver: bridge


services:

  buggy-rabbitmq:
    image: rabbitmq:3-management
    container_name: buggy-rabbitmq
    hostname: buggy-rabbitmq
    ports:
      - 5672
      - 5671
      - 15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_VHOST: buggy
    networks:
      - buggy-networks

  buggy-mysql-zipkin:
    image: openzipkin/zipkin-mysql
    container_name: buggy-mysql-zipkin
    hostname: buggy-mysql-zipkin
    networks:
      - buggy-networks


  buggy-mongo:
    image: mongo:4.0.4
    container_name: buggy-mongo
    hostname: buggy-mongo
    ports:
      - 27017:27017
    networks:
      - buggy-networks

  buggy-zipkin:
    image: openzipkin/zipkin
    container_name: buggy-zipkin
    # Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=buggy-mysql-zipkin
      - RABBIT_ADDRESSES=buggy-rabbitmq
      - RABBIT_USER=admin
      - RABBIT_PASSWORD=admin
      - RABBIT_VIRTUAL_HOST=buggy
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411
    depends_on:
      - buggy-mysql-zipkin
      - buggy-rabbitmq
    networks:
      - buggy-networks

  buggy-developer-service:
    build:
      context: ./developer
      args:
        JAR_FILE: build/libs/*.jar
    deploy:
      replicas: 2
    depends_on:
      - buggy-mongo
      - buggy-rabbitmq
    container_name: buggy-developer-service
    hostname: buggy-developer-service
    ports:
      - 8080
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8080
    networks:
      - buggy-networks

  buggy-issues-service:
    build:
      context: ./issues
      args:
        JAR_FILE: build/libs/*.jar
    deploy:
      replicas: 2
    depends_on:
      - buggy-mongo
      - buggy-rabbitmq
    container_name: buggy-issues-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8080
    hostname: buggy-issues-service
    ports:
      - 8080
    networks:
      - buggy-networks

  buggy-planning-service:
    build:
      context: ./planning
      args:
        JAR_FILE: build/libs/*.jar
    deploy:
      replicas: 2
    depends_on:
      - buggy-mongo
      - buggy-rabbitmq
    container_name: buggy-planning-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8080
    hostname: buggy-planning-service
    ports:
      - 8080
    networks:
      - buggy-networks

  buggy-gateway-service:
    build:
      context: ./gateway
      args:
        JAR_FILE: build/libs/*.jar
    depends_on:
      - buggy-developer-service
      - buggy-issues-service
      - buggy-planning-service
    container_name: buggy-gateway-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8080
    hostname: buggy-gateway-service
    ports:
      - 8080
    networks:
      - buggy-networks