version: '3.5'

networks:
  buggy-networks:
    driver: bridge


services:
#
#  buggy-rabbitmq:
#    image: rabbitmq:3-management
#    container_name: buggy-rabbitmq
#    hostname: buggy-rabbitmq
#    ports:
#      - 5672
#      - 5671
#      - 15672
#    environment:
#      RABBITMQ_DEFAULT_USER: admin
#      RABBITMQ_DEFAULT_PASS: admin
#      RABBITMQ_DEFAULT_VHOST: buggy
#    volumes:
#      - ./rabbitmq/etc/enabled_plugins:/etc/rabbitmq/enabled_plugins
#    networks:
#      - buggy-networks

#  buggy-mysql-zipkin:
#    image: openzipkin/zipkin-mysql
#    container_name: buggy-mysql-zipkin
#    hostname: buggy-mysql-zipkin
#    networks:
#      - buggy-networks


  buggy-mongo:
    image: mongo:4.0.4
    container_name: buggy-mongo
    hostname: buggy-mongo
    ports:
      - 27017
    networks:
      - buggy-networks

  buggy-postgres:
    image: postgres:12.1
    container_name: buggy-postgres
    hostname: buggy-postgres
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=buggy
    networks:
      - buggy-networks

#  buggy-zipkin:
#    image: openzipkin/zipkin
#    container_name: buggy-zipkin
#    hostname: buggy-zipkin
#    # Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables
#    environment:
#      - STORAGE_TYPE=mysql
#      - MYSQL_HOST=buggy-mysql-zipkin
#      - RABBIT_ADDRESSES=buggy-rabbitmq
#      - RABBIT_USER=admin
#      - RABBIT_PASSWORD=admin
#      - RABBIT_VIRTUAL_HOST=buggy
#    deploy:
#      restart_policy:
#        condition: on-failure
#        delay: 30s
#        max_attempts: 3
#    ports:
#      # Port used for the Zipkin UI and HTTP Api
#      - 9411
#    depends_on:
#      - buggy-mysql-zipkin
#      - buggy-rabbitmq
#    networks:
#      - buggy-networks

  buggy-keycloak:
    image: jboss/keycloak:8.0.1
    container_name: buggy-keycloak
    hostname: buggy-keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=buggy-postgres
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_DATABASE=buggy
      - KEYCLOAK_IMPORT=/tmp/buggy_realm.json
      - JAVA_OPTS=-Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true  --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED --add-exports=jdk.unsupported/sun.reflect=ALL-UNNAMED -Dkeycloak.profile.feature.upload_scripts=enabled
    volumes:
      - ./keycloak:/tmp
    ports:
      - 8080
    depends_on:
      - buggy-postgres
    networks:
      - buggy-networks


#  buggy-sba-service:
#    build:
#      context: ./sba-server
#      args:
#        JAR_FILE: build/libs/*.jar
#    container_name: buggy-sba-service
#    hostname: buggy-sba-service
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
#      SERVER_PORT: 8080
#    deploy:
#      replicas: 1
#      restart_policy:
#        condition: on-failure
#        delay: 15s
#    ports:
#      - 8080
#    networks:
#      - buggy-networks


#  buggy-elasticsearch:
#    image: elasticsearch:7.5.1
#    container_name: buggy-elasticsearch
#    hostname: buggy-elasticsearch
#    environment:
#      discovery.type: single-node
#    ports:
#      - 9200
#      - 9300
#    networks:
#      - buggy-networks
#
#  buggy-kibana:
#    image: kibana:7.5.1
#    container_name: buggy-kibana
#    hostname: buggy-kibana
#    environment:
#      SERVER_NAME: buggy-kibana
#      ELASTICSEARCH_HOSTS: http://buggy-elasticsearch:9200
#    ports:
#      - 5601
#    networks:
#      - buggy-networks
#
#
#  buggy-prometheus:
#    image:  prom/prometheus:v2.15.2
#    container_name: buggy-prometheus
#    hostname: buggy-prometheus
#    volumes:
#      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#    ports:
#      - 9090
#    networks:
#      - buggy-networks
#
#
#  buggy-prometheus-pushgateway:
#    image:  prom/pushgateway
#    container_name: buggy-prometheus-pushgateway
#    hostname: buggy-prometheus-pushgateway
#    ports:
#      - 9091
#    depends_on:
#      - buggy-prometheus
#    networks:
#      - buggy-networks


  buggy-zookeeper:
    image: confluentinc/cp-zookeeper:5.3.1
    container_name: buggy-zookeeper
    hostname: buggy-zookeeper
    ports:
      - 2181
    networks:
      - buggy-networks
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000


  buggy-broker:
    image: confluentinc/cp-enterprise-kafka:5.3.1
    hostname: buggy-broker
    container_name: buggy-broker
    depends_on:
      - buggy-zookeeper
    ports:
      - 9092
    networks:
      - buggy-networks
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'buggy-zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://buggy-broker:29092,PLAINTEXT_HOST://buggy-broker:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: buggy-broker:29092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: buggy-zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'


  buggy-kafka-schema-registry:
    image: confluentinc/cp-schema-registry:5.3.1
    hostname: buggy-kafka-schema-registry
    container_name: buggy-kafka-schema-registry
    depends_on:
      - buggy-zookeeper
      - buggy-broker
    ports:
      - "8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: buggy-kafka-schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'buggy-zookeeper:2181'
    networks:
      - buggy-networks

  buggy-kafka-rest:
    image: confluentinc/cp-kafka-rest
    container_name: buggy-kafka-rest
    hostname: buggy-kafka-rest
    ports:
      - "8082"
    depends_on:
      - buggy-zookeeper
      - buggy-broker
      - buggy-kafka-schema-registry
    networks:
      - buggy-networks
    environment:
      KAFKA_REST_HOST_NAME: buggy-kafka-rest
      KAFKA_REST_BOOTSTRAP_SERVERS: 'buggy-broker:29092'
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
      KAFKA_REST_SCHEMA_REGISTRY_URL: 'http://buggy-kafka-schema-registry:8081'




  buggy-kafka-connect:
    image: cnfldemos/kafka-connect-datagen:0.1.3-5.3.1
    hostname: buggy-kafka-connect
    container_name: buggy-kafka-connect
    depends_on:
      - buggy-zookeeper
      - buggy-broker
      - buggy-kafka-schema-registry
    ports:
      - "8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 'buggy-broker:29092'
      CONNECT_REST_ADVERTISED_HOST_NAME: buggy-kafka-connect
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://buggy-kafka-schema-registry:8081
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_ZOOKEEPER_CONNECT: 'buggy-zookeeper:2181'
      # CLASSPATH required due to CC-2422
      CLASSPATH: /usr/share/java/monitoring-interceptors/monitoring-interceptors-5.3.1.jar
      CONNECT_PRODUCER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
      CONNECT_CONSUMER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
      CONNECT_LOG4J_LOGGERS: org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR
    networks:
      - buggy-networks

  buggy-kafka-ksql-server:
    image: confluentinc/cp-ksql-server:5.3.1
    hostname: buggy-kafka-ksql-server
    container_name: buggy-kafka-ksql-server
    depends_on:
      - buggy-broker
      - buggy-kafka-connect
    ports:
      - "8088"
    environment:
      KSQL_CONFIG_DIR: "/etc/ksql"
      KSQL_LOG4J_OPTS: "-Dlog4j.configuration=file:/etc/ksql/log4j-rolling.properties"
      KSQL_BOOTSTRAP_SERVERS: "buggy-broker:29092"
      KSQL_HOST_NAME: buggy-ksql-server
      KSQL_LISTENERS: "http://0.0.0.0:8088"
      KSQL_CACHE_MAX_BYTES_BUFFERING: 0
      KSQL_KSQL_SCHEMA_REGISTRY_URL: "http://buggy-kafka-schema-registry:8081"
      KSQL_PRODUCER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
      KSQL_CONSUMER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"
    networks:
      - buggy-networks

  buggy-kafka-control-center:
    image: confluentinc/cp-enterprise-control-center:5.3.1
    hostname: buggy-kafka-control-center
    container_name: buggy-kafka-control-center
    depends_on:
      - buggy-zookeeper
      - buggy-broker
      - buggy-kafka-schema-registry
      - buggy-kafka-connect
      - buggy-kafka-ksql-server
    ports:
      - "9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'buggy-broker:29092'
      CONTROL_CENTER_ZOOKEEPER_CONNECT: 'buggy-zookeeper:2181'
      CONTROL_CENTER_CONNECT_CLUSTER: 'buggy-kafka-connect:8083'
      CONTROL_CENTER_KSQL_URL: "http://buggy-kafka-ksql-server:8088"
      CONTROL_CENTER_KSQL_ADVERTISED_URL: "http://buggy-kafka-ksql-server:8088"
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://buggy-kafka-schema-registry:8081"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021
    networks:
      - buggy-networks