spring:
  main:
    banner-mode: "off"
  application:
    name: buggy-issues-service
  profiles:
    active: local
  jackson:
    time-zone: UTC
  cloud:
    stream:
      bindings:
        output:
          destination: issues

  kafka:
    producer:
      client-id: ${spring.application.name}
  data:
    mongodb:
      database: buggy-issues
  zipkin:
    sender:
      type: kafka
  sleuth:
    messaging:
      enabled: true
    sampler:
      probability: 100


management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /
  endpoint:
    health:
      show-details: always
      enabled: true
  trace:
    http:
      include: REQUEST_HEADERS,RESPONSE_HEADERS,TIME_TAKEN,PRINCIPAL

