info:
  component: A simple API Gateway Service

spring:
  main:
    banner-mode: "off"
  profiles:
    active: local
  application:
    name: buggy-gateway-service
  jackson:
    time-zone: UTC
  zipkin:
    sender:
      type: rabbit
  rabbitmq:
    port: 5672
    virtualHost: buggy

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /
  endpoint:
    health:
      show-details: always
      enabled: true

