spring:
  rabbitmq:
    host: buggy-rabbitmq
    password: admin
    username: admin
  cloud:
    gateway:
      routes:
      - id: developers
        uri: http://buggy-developer-service:8080
        predicates:
        - Path=/developers/**
      - id: issues
        uri: http://buggy-issues-service:8080
        predicates:
        - Path=/stories/**, /bugs/**
      - id: planning
        uri: http://buggy-planning-service:8080
        predicates:
        - Path=/planning/**
  sleuth:
    messaging:
      enabled: true
    sampler:
      probability: 100

logging:
  level:
    root: info

