spring:
  data:
    mongodb:
      host: buggy-mongo
  rabbitmq:
    host: buggy-rabbitmq
    password: admin
    username: admin
  boot:
    admin:
      client:
        url: http://buggy-sba-service:8080
        instance:
          prefer-ip: true
  security:
    oauth2:
      resourceserver:
        resourceid: buggyui
        jwt:
          verifierKey: -----BEGIN PUBLIC KEY----- MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApVNkQ3Xj7egSMWEt9lV36SygAcslb+ENFTkqhpPIT6P0v4R1LWv90mzHrTOVbZ5ZPLjoe+BI0s1pr5Ok5hZhoTaT0jCXC7rc9q436IYpEthRofTYPXAyBR8YH1tvi7VTjlc5AEhRb+py8cmhEgXp+rnWuIBQEkz/AnW/S+4BIKQMfIpP4a1iIw9mdnKUHZVJWtZF2H6uFZH+8ealS5yGrhgonhmZjEFy82qqUT0UzcbX5AGB1SUPpXqTzOvA++mRGnFShMRPCcFg2PVlpXnxH0fp4n+FKJ9RLSe9/1Aj/X7HNUWAyPVaVaEQOiZNiN8lAb94I9nK2eeUOkt1VV7S6QIDAQAB -----END PUBLIC KEY-----
