spring:
  main:
    banner-mode: "off"
  application:
    name: buggy-developer-spring-service
  profiles:
    active: local
  jackson:
    time-zone: UTC
  cloud:
    stream:
      bindings:
        output:
          destination: developers
  data:
    mongodb:
      database: buggy-developers
  zipkin:

    sender:
      type: kafka
    enabled: true
  sleuth:

    messaging:
      enabled: true
    sampler:
      probability: 100
  kafka:
    producer:
      client-id: ${spring.application.name}



management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /
  endpoint:
    health:
      show-details: always
      enabled: true
  trace:
    http:
      include: REQUEST_HEADERS,RESPONSE_HEADERS,TIME_TAKEN,PRINCIPAL
  metrics:
    export:
      prometheus:
        pushgateway:
          base-url: buggy-prometheus-pushgateway:9091
          enabled: true
          job: buggy-developer-spring-service
          push-rate: 30s
    tags:
      application: buggy-developer-spring-service
      stage: dev



