spring:
  main:
    banner-mode: "off"
  application:
    name: buggy-developer-spring-service
  profiles:
    active: local
  jackson:
    time-zone: UTC
  cloud:
    stream:
      bindings:
        output:
          destination: developers
  data:
    mongodb:

      database: buggy-developers
  zipkin:
    propagation-keys:
      - CorrId
    sender:
      type: kafka
    enabled: true
  sleuth:

    propagation-keys:
      - CorrId
    messaging:
      enabled: true
    sampler:
      probability: 1.0
    log:
      slf4j:
        whitelisted-mdc-keys: CorrId
  kafka:
    producer:
      client-id: ${spring.application.name}



management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /
  endpoint:
    health:
      show-details: always
      enabled: true
  trace:
    http:

      include: REQUEST_HEADERS,RESPONSE_HEADERS,TIME_TAKEN,PRINCIPAL
  metrics:
    export:
      prometheus:
        pushgateway:
          enabled: true
          job: buggy-developer-spring-service
          push-rate: 30s
    tags:
      application: buggy-developer-spring-service
      stage: dev


logging:
  level:
    root: warn
    org.apache.kafka.clients.producer.ProducerConfig: warn
    org.apache.kafka.clients.consumer.ConsumerConfig: warn
server:
  port: 8081
