spring:
  data:
    mongodb:
      uri: mongodb://${embedded.mongodb.host}:${embedded.mongodb.port}/${embedded.mongodb.database}

  boot:
    admin:
      client:
        enabled: false
  zipkin:
    enabled: false

  sleuth:
    enabled: false

management:
  endpoints:
    enabled-by-default: false
  metrics:
    export:
      prometheus:
        pushgateway:
          enabled: false

logging:
  level:
    root: info
#    org.springframework.boot.autoconfigure.mongo.embedded: trace
#    org.springframework.web: debug
#    org.mongodb: trace
#    com.playtika.testcontainers: trace