spring:
  data:
    mongodb:
      host: localhost

  boot:
    admin:
      client:
        enabled: false
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost

  zipkin:
    enabled: true
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    org.springframework.cloud.stream: warn
    org.springframework.web: trace
    org.springframework.security: trace
    org.keycloak: trace




management:
  metrics:
    export:
      prometheus:
        pushgateway:
          base-url: localhost:9091

          enabled: false
        enabled: false
keycloak:
  auth-server-url: http://localhost:8080/auth
  allow-any-hostname: true
  cors: false
  realm: buggy
  resource: buggyui
  verify-token-audience: false
  bearer-only: true
  use-resource-role-mappings: false
  principal-attribute: preferred_username
  public-client: true
