name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build planning-spring
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          build-root-directory: planning-spring
          wrapper-directory: planning-spring
          gradle-version: 7.2
          arguments: build
      - name: build planning-quarkus
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          build-root-directory: planning-quarkus
          wrapper-directory: planning-quarkus
          gradle-version: 7.2
          arguments: build
      - name: build developer-spring
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          build-root-directory: developer-spring
          wrapper-directory: developer-spring
          gradle-version: 7.2
          arguments: build
      - name: build developer-quarkus
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          build-root-directory: developer-quarkus
          wrapper-directory: developer-quarkus
          gradle-version: 7.2
          arguments: build
      - name: build issues-spring
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          build-root-directory: issues-spring
          wrapper-directory: issues-spring
          gradle-version: 7.2
          arguments: build
