name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt-openj9'
          java-version: '16'
          cache: 'gradle'
      - name: build planning-spring
        working-directory: ./developer-spring
        run: ./gradlew --info build
      - name: build developer-spring
        working-directory: ./planning-spring
        run: ./gradlew --info build
      - name: build issues-spring
        working-directory: ./issues-spring
        run: ./gradlew --info build
