name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: build developer
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: eskatos/gradle-command-action@v1
      with:
        build-root-directory: developer
        wrapper-directory: developer
        gradle-version: 5.6.2
        arguments: build
    - name: build issues
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: eskatos/gradle-command-action@v1
      with:
        build-root-directory: issues
        wrapper-directory: issues
        gradle-version: 5.6.2
        arguments: build
    - name: build planning
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: eskatos/gradle-command-action@v1
      with:
        build-root-directory: planning
        wrapper-directory: planning
        gradle-version: 5.6.2
        arguments: build
